# Generated by Django 4.2.25 on 2025-11-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_alter_coresettings_default_time_zone"),
    ]

    operations = [
        # Windows agent URLs
        migrations.AddField(
            model_name="coresettings",
            name="agent_win_url_amd64",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="agent_win_url_386",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="agent_win_url_arm64",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        # Linux agent URLs
        migrations.AddField(
            model_name="coresettings",
            name="agent_linux_url_amd64",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="agent_linux_url_arm64",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="agent_linux_url_arm",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        # macOS agent URLs
        migrations.AddField(
            model_name="coresettings",
            name="agent_darwin_url_amd64",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="agent_darwin_url_arm64",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="agent_darwin_url_universal",
            field=models.CharField(max_length=500, null=True, blank=True),
        ),
    ]
